### ISSUE TITLE
a bug in the code

### ISSUE THREAD

**Issue by yanyiss** [Q-Minh/projective-dynamics#1]
row 32 in the pre_draw_handler.cpp should be fext->col(1).array() -=
            physics_params->mass_per_particle*(physics_params->is_gravity_active ? 9.81 : 0.), isn't it?

**Comment by Q-Minh** [comment]
Hi yanyiss, thanks for letting me know, you're absolutely right! I guess the code would only work for a unit particle mass. :) I'll change it. For your information, this codebase is very old and at some point, I will take the time to publish a public version of a much cleaner/better projective dynamics implementation!
